# Pages CMS Configuration for RV Link Documentation Site
# https://pagescms.org

name: RV Link Docs

media:
  input: src/assets
  output: src/assets

components:
  metadata:
    label: Page Metadata
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true

content:
  # ---------------------------------------
  # Start Here (root docs)
  # ---------------------------------------
  - name: start-here
    label: "🚀 Start Here"
    type: collection
    path: src/content/docs
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: head
        label: HTML Head Meta Tags
        type: list
        fields:
          - name: tag
            label: Tag Name
            type: string
          - name: attrs
            label: Attributes
            type: map
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Getting Started
  # ---------------------------------------
  - name: getting-started
    label: "📖 Getting Started"
    type: collection
    path: src/content/docs/getting-started
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Installation
  # ---------------------------------------
  - name: installation
    label: "🛠️ Installation"
    type: collection
    path: src/content/docs/installation
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Hardware
  # ---------------------------------------
  - name: hardware
    label: "🔌 Hardware"
    type: collection
    path: src/content/docs/hardware
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Configuration
  # ---------------------------------------
  - name: configuration
    label: "⚙️ Configuration"
    type: collection
    path: src/content/docs/configuration
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Automation
  # ---------------------------------------
  - name: automation
    label: "🤖 Automation"
    type: collection
    path: src/content/docs/automation
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Monitoring
  # ---------------------------------------
  - name: monitoring
    label: "📊 Monitoring"
    type: collection
    path: src/content/docs/monitoring
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Troubleshooting
  # ---------------------------------------
  - name: troubleshooting
    label: "🔧 Troubleshooting"
    type: collection
    path: src/content/docs/troubleshooting
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Core Concepts
  # ---------------------------------------
  - name: concepts
    label: "💡 Concepts"
    type: collection
    path: src/content/docs/concepts
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text